name: ts-zod

on: [push]

jobs:
  ts_zod:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nodejs: [14]

    steps:
    - uses: actions/checkout@v2

    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.nodejs }}

    - run: |
        npm -g install yarn
        yarn install
        yarn add -D esbuild
        yarn test
      working-directory: ./ts_zod
